services:
  #Our PostgreSQL database service
    db:
      # The Docker image of postgres -- we're using the latest.
      image: postgres:latest
      # The parts to expose to the host container
      # 5432 is the default PostgreSQL ports
      ports:
        - "5432:5432"
      # If we accidentally kill the running container, Docker Compose will restart it
      restart: always
      # The PostgreSQL Docker container uses environment variables to read configuration, here we set the password.
      # - Do NOT store plaintext passwords in source control. We do so here as this is a builder.
      environment:
        POSTGRES_PASSWORD: changemeinprod! #The password that we specify in our Spring Boot configuration later
        #Without volumes, we will lose all the data in the database. OK for development environment.